<?php

namespace Bundles\StoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function findPh($log)
    {
        $qb=$this->createQueryBuilder('u')
            ->select("u")
            ->where('u. =:log')
            ->andWhere("u.access='public'")
            ->setParameter('log','%'.$log.'%');
        return($qb->getQuery()->getResult());
    }

}
