
app_front_end_wellcome:
    path:     /
    defaults: { _controller: AppFrontEndBundle:Page:index }

app_front_end_pag:
    path:     /pagin
    defaults: { _controller: AppFrontEndBundle:Page:pagin }

app_front_end_bread:
    path:     /bread
    defaults: { _controller: AppFrontEndBundle:Page:bread }

app_front_end_multi:
    path:     /multi
    defaults:
        _controller: AppFrontEndBundle:Page:multi

app_front_end_seller:
    path:     /seller
    defaults: { _controller: AppFrontEndBundle:Page:seller }

app_front_end_test:
    path:  /test
    defaults: { _controller: AppFrontEndBundle:Page:test }

app_front_end_catalog:
    path: /catalog
    defaults: { _controller: AppFrontEndBundle:Page:catalog }
    requirements:
           _method: POST|GET

app_front_end_photograph:
    path: /photograph/{id}
    defaults: { _controller: AppFrontEndBundle:Page:photograph }
    requirements:
           _method: POST|GET

app_front_end_returnlink:
    path:     /retlink
    defaults: { _controller: AppFrontEndBundle:Page:linkReturn}

app_front_end_approveOrder:
      path: /approve
      defaults: { _controller: AppFrontEndBundle:Page:approveOrder}
      requirements:
             _method: POST|GET

app_front_end_addus:
    path:     /addus
    defaults: { _controller: AppFrontEndBundle:Page:addUser}

app_front_end_stat:
    path: /afestat
    defaults: { _controller: AppFrontEndBundle:Page:showStat}




app_front_end_svImg:
    path: /sv
    defaults: { _controller: AppFrontEndBundle:Image:save }
    requirements:
           _method: POST|GET

app_front_end_delImg:
    path: /delImg
    defaults: { _controller: AppFrontEndBundle:Image:delete }
    requirements:
           _method: POST|GET

app_front_end_fotosess:
    path:     /fotosess
    defaults: { _controller: AppFrontEndBundle:Image:fotoSess}

app_front_end_savefotosess:
    path:     /savefotosess
    defaults: { _controller: AppFrontEndBundle:Image:saveFotoSess}

app_front_end_dpfs:
    path:     /dpfs
    defaults: { _controller: AppFrontEndBundle:Image:displayProposFs}

app_front_end_orderfs:
    path:     /orderfotosess
    defaults: { _controller: AppFrontEndBundle:Image:orderFs}

app_front_end_orderimg:
      path: /orderimg
      defaults: { _controller: AppFrontEndBundle:Image:order}

app_front_end_waterimg:
      path: /waterimg
      defaults: { _controller: AppFrontEndBundle:Image:waterimg}




app_front_end_profedit:
      path: /profedit
      defaults: { _controller: AppFrontEndBundle:User:index}




app_front_end_search:
    path: /search
    defaults: { _controller: AppFrontEndBundle:Search:search }
    requirements:
           _method: POST|GET




app_front_end_ajax:
    path:     /ajaxSS
    defaults: { _controller: AppFrontEndBundle:Ajax:saveStatus}

app_front_end_ajaxCheckUser:
    path: /ajaxCU
    defaults: { _controller: AppFrontEndBundle:Ajax:checkUser}
    requirements:
           _method: POST|GET