Bundles\StoreBundle\Entity\Orders:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        status:
            type: string
            length: '50'
    manyToOne:
        users:
            targetEntity: Users
            inversedBy: orders
            joinColumn:
              name: userId
              referencedColumnName: id
        user2:
            targetEntity: User2
            inversedBy: orders
            joinColumn:
              name: user2Id
              referencedColumnName: id
        photo:
            targetEntity: Photo
            inversedBy: orders
            joinColumn:
              name: photoId
              referencedColumnName: id

    lifecycleCallbacks: {  }
