Bundles\StoreBundle\Entity\Photo:
    type: entity
    table: photo
    repositoryClass: Bundles\StoreBundle\Entity\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adress:
            type: string
            length: '255'
        date:
            type: datetime
    manyToOne:
        users:
          targetEntity: Users
          inversedBy: photo
          joinColumn:
            name: userId
            referencedColumnName: id
        user2:
          targetEntity: User2
          inversedBy: photo
          joinColumn:
            name: user2Id
            referencedColumnName: id
    oneToMany:
        orders:
            targetEntity: Orders
            mappedBy: photo
    lifecycleCallbacks: {  }
