Bundles\StoreBundle\Entity\User2:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: '40'
        lastname:
            type: string
            length: '50'
        username:
            type: string
            length: '40'
        password:
            type: string
            length: '255'
        salt:
            type: string
            length: 255
        email:
            type: string
            length: '100'
        status:
            type: string
            length: '20'
        img:
            type: string
            length: '255'
            nullable: true


    lifecycleCallbacks: {  }
