services:
#    bundles_login.example:
#        class: Bundles\LoginBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     site_bundle.helper:
               class:  Bundles\LoginBundle\Service\Helper
               arguments:
                   - @service_container
