<?php

namespace Bundles\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User2Repository extends EntityRepository
{
       public function findLog($log)
       {
           $qb=$this->createQueryBuilder('u')
               ->select("u")
               ->where('u.username LIKE :log')
               ->andWhere("u.status='photo'")
               ->setParameter('log','%'.$log.'%');
           return($qb->getQuery()->getResult());
       }


}
